(()=>{
const U='https://ziiivcuynidpmvosxvkj.supabase.co',K='sb_publishable_GeK1Fvfdhv6vQrcWjgeULQ_kc6lEY9U';
const css=`.ch-health{width:100%;margin:10px 0 14px;padding:12px 14px;border-radius:16px;border:1px solid #24456d;background:#0f1d31;color:#dceaff;text-align:left;font:inherit}.ch-health b{display:block;font-size:13px}.ch-health small{display:block;margin-top:4px;color:#92a8c8}.ch-meter{height:7px;background:#0b1525;border-radius:999px;overflow:hidden;margin-top:9px}.ch-meter span{display:block;height:100%;background:linear-gradient(90deg,#57c7ff,#73e4ad);border-radius:999px}.ch-modal{position:fixed;inset:0;z-index:9999;background:#06101beF;padding:18px;overflow:auto;color:#f7f9fc}.ch-sheet{max-width:720px;margin:auto;background:#0e1a2c;border:1px solid #29456d;border-radius:20px;padding:16px}.ch-head{display:flex;justify-content:space-between;gap:10px;align-items:center}.ch-close{border:1px solid #315074;background:#15253d;color:#fff;border-radius:10px;padding:8px 11px}.ch-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:8px;margin-top:12px}.ch-grid>div{background:#0b1525;border:1px solid #213655;border-radius:13px;padding:10px}.ch-grid small{display:block;color:#8da0be;font-size:10px}.ch-grid strong{display:block;font-size:19px;margin-top:3px}.ch-note{color:#9eafca;font-size:12px;line-height:1.45}.ch-bad{color:#ffb1b6}.ch-good{color:#89f2c1}@media(max-width:430px){.ch-grid{grid-template-columns:repeat(2,1fr)}}`;
const style=document.createElement('style');style.textContent=css;document.head.appendChild(style);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function get(t,q='select=*'){const r=await fetch(`${U}/rest/v1/${t}?${q}`,{headers:{apikey:K},cache:'no-store'});if(!r.ok)throw Error(`${t} HTTP ${r.status}`);return r.json()}
let status=null,btn;
function healthy(s){return Number(s.stale_ready_deals||0)===0&&Number(s.high_coverage_gaps||0)===0}
function renderButton(){if(!btn||!status)return;const ok=healthy(status),score=Math.max(0,Math.min(100,Math.round(Number(status.avg_ready_verification_score||0))));btn.innerHTML=`<b>${ok?'🟢':'🟠'} Engine ${ok?'healthy':'needs attention'} • ${Number(status.active_sources||0)} sources</b><small>${Number(status.ready_deals||0)} ready • ${Number(status.verifying_deals||0)} verifying • ${Number(status.verified_stacks||0)} stacks • ${Number(status.open_coverage_gaps||0)} coverage gaps</small><div class="ch-meter"><span style="width:${score}%"></span></div>`}
function show(){if(!status)return;const ok=healthy(status),m=document.createElement('div');m.className='ch-modal';m.innerHTML=`<div class="ch-sheet"><div class="ch-head"><div><b>${ok?'🟢 Engine healthy':'🟠 Engine needs attention'}</b><div class="ch-note">Live intelligence status from Coupon Hunt HQ</div></div><button class="ch-close">Close</button></div><div class="ch-grid"><div><small>Ready</small><strong>${Number(status.ready_deals||0)}</strong></div><div><small>Verifying</small><strong>${Number(status.verifying_deals||0)}</strong></div><div><small>Verification score</small><strong>${Math.round(Number(status.avg_ready_verification_score||0))}%</strong></div><div><small>Active sources</small><strong>${Number(status.active_sources||0)}</strong></div><div><small>Verified stacks</small><strong>${Number(status.verified_stacks||0)}</strong></div><div><small>Coverage gaps</small><strong>${Number(status.open_coverage_gaps||0)}</strong></div><div><small>Stale ready</small><strong class="${Number(status.stale_ready_deals||0)?'ch-bad':'ch-good'}">${Number(status.stale_ready_deals||0)}</strong></div><div><small>Replacement queue</small><strong>${Number(status.replacement_queue||0)}</strong></div><div><small>Blocked</small><strong>${Number(status.blocked_deals||0)}</strong></div><div><small>Expired</small><strong>${Number(status.expired_deals||0)}</strong></div><div><small>Evidence 24h</small><strong>${Number(status.evidence_24h||0)}</strong></div><div><small>Changes 24h</small><strong>${Number(status.changes_24h||0)}</strong></div></div><p class="ch-note">Stale deals are automatically sent back for checking. Coverage gaps flag sources that have not been serviced on schedule. A high verification score never overrides missing mandatory terms.</p></div>`;m.querySelector('.ch-close').onclick=()=>m.remove();m.onclick=e=>{if(e.target===m)m.remove()};document.body.appendChild(m)}
async function refresh(){try{const rows=await get('coupon_hunt_intelligence_status');status=rows[0]||{};renderButton()}catch(e){if(btn)btn.innerHTML=`<b>🟠 Engine status unavailable</b><small>${esc(e.message)} • deals can still use their normal live feed</small>`}}
function mount(){if(document.querySelector('.ch-health'))return;btn=document.createElement('button');btn.className='ch-health';btn.innerHTML='<b>🟡 Engine health • loading…</b><small>Checking verification, sources and stacks</small>';btn.onclick=show;const tabs=document.querySelector('.tabs'),hero=document.querySelector('.score');if(tabs)tabs.parentNode.insertBefore(btn,tabs);else if(hero)hero.after(btn);else document.querySelector('main')?.prepend(btn);refresh();setInterval(refresh,300000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh()})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();
})();