(()=>{'use strict';
const DATA_URL='./data.json',CACHE_KEY='coupon-hunt-data-v6',STATE_KEY='coupon-hunt-state-v6',META_KEY='coupon-hunt-deal-meta-v6',LOCAL_CLAIMS_KEY='coupon-hunt-local-claims-v6';
let DATA=null,deferredInstall=null,dealMeta={},CURRENT_SHOP='all';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const safeUrl=u=>/^https?:\/\//i.test(String(u||''))?String(u):'';
const load=(k,d)=>{try{return JSON.parse(localStorage.getItem(k)||'null')??d}catch{return d}};
const save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
let STATE=Object.assign({favourites:[],basket:[],usedCoupons:[],watchedSubs:[],alerts:false,lastNotify:''},load(STATE_KEY,{}));
const stateSave=()=>save(STATE_KEY,STATE);
const hash=s=>{let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return (h>>>0).toString(36)};
const dealKey=d=>hash([d.deal,d.code,d.where].join('|')),couponKey=c=>hash([c.brand,c.coupon,c.expiry].join('|')),subKey=s=>hash([s.brand,s.product,s.dealId].join('|'));
const signature=d=>hash([d.status,d.deal,d.price,d.save,d.code,d.where,d.stack,d.rule,d.expires,d.dealLink,d.terms].join('|'));
function ensureV6Css(){if(!document.querySelector('link[href*="app.css?v=6"]')){const l=document.createElement('link');l.rel='stylesheet';l.href='./app.css?v=6';document.head.appendChild(l)}}
function upgradeShell(){const view=document.body.dataset.view||'deals';$$('.nav a').forEach(a=>{if(a.textContent.includes('Deals'))a.href='./app.html'});const hero=$('.hero');if(hero&&!$('#alertsBtn')){const actions=hero.querySelector('.actions');const b=document.createElement('button');b.id='alertsBtn';b.className='round';b.title='Deal alerts';b.textContent='🔔';actions.insertBefore(b,actions.firstChild)}const sync=$('.sync');if(sync&&!$('#stats')){const stats=document.createElement('div');stats.id='stats';stats.className='stats';sync.insertAdjacentElement('afterend',stats);const insight=document.createElement('div');insight.id='insight';insight.className='insight';stats.insertAdjacentElement('afterend',insight)}if(view==='deals'){if(!$('#search')){$('.top').insertAdjacentHTML('beforeend','<div class="search"><input id="search" type="search" placeholder="Search deal, brand or shop…" autocomplete="off"></div>')}let f=$('.filters');if(!f){f=document.createElement('div');f.className='filters';$('.top').appendChild(f)}f.innerHTML='<button class="chip active" data-filter="best">Best</button><button class="chip" data-filter="all">All</button><button class="chip" data-filter="free">Free</button><button class="chip" data-filter="50">50%+</button><button class="chip" data-filter="pet">Pets</button><button class="chip" data-filter="food">Food</button><button class="chip" data-filter="cleaning">Cleaning</button><button class="chip" data-filter="stack">Stacks</button><button class="chip" data-filter="saved">⭐ Saved</button><button class="chip" data-filter="basket">🛒 Basket</button>';document.body.dataset.filter='best';if(!$('#shopSelect'))f.insertAdjacentHTML('afterend','<div class="shopbar"><label>🏪 Shop <select id="shopSelect"><option value="all">All shops</option></select></label><button class="mini" id="markSeen">Clear NEW</button></div>')}if(!$('#appModal'))document.body.insertAdjacentHTML('beforeend','<dialog id="appModal"><div class="modalHead"><h2 id="modalTitle">Details</h2><button class="close" data-close-modal>✕</button></div><div class="modalBody" id="modalBody"></div></dialog>')}
function setSync(k,m){if($('#syncDot'))$('#syncDot').className='dot '+k;if($('#syncText'))$('#syncText').textContent=m}
function parseMoney(v){const m=String(v||'').replace(/,/g,'').match(/£\s*([0-9]+(?:\.[0-9]+)?)/);return m?Number(m[1]):null}
function parseDate(v){const s=String(v||'').trim();let m;if((m=s.match(/^(\d{4})-(\d{2})-(\d{2})$/)))return new Date(+m[1],+m[2]-1,+m[3],23,59,59);if((m=s.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/)))return new Date(+m[3],+m[2]-1,+m[1],23,59,59);if((m=s.match(/^(\d{1,2})\s+([A-Za-z]{3,9})\s+(\d{4})$/))){const d=new Date(m[2]+' '+m[1]+', '+m[3]+' 23:59:59');return isNaN(d)?null:d}return null}
function daysLeft(v){const d=parseDate(v);if(!d)return null;const now=new Date();now.setHours(0,0,0,0);return Math.floor((d-now)/86400000)}
function expiryBadge(d){const n=daysLeft(d.expires);if(n===null)return'';if(n<0)return'EXPIRED';if(n===0)return'ENDS TODAY';if(n===1)return'ENDS TOMORROW';if(n<=3)return n+' DAYS LEFT';return''}
function dealClass(s){s=String(s||'');return s.includes('UPCOMING')?'upcoming':s.includes('CHECK')?'check':'use'}
function stackClass(s){s=String(s||'');return s.includes('YES')?'yes':s.includes('NO')?'no':'warn'}
function category(d){const x=(d.deal+' '+d.where).toLowerCase();if(/pet|dog|cat|puppy|kitten|blink|forthglade|tails|pooch|burns|harringtons|zooplus|scrumbles|lily|thrive|naturediet|different dog|vet's kitchen/.test(x))return'pet';if(/vax|clean|laundry|smol|method|delphis|astonish|kärcher/.test(x))return'cleaning';if(/food|drink|pepsi|kellogg|spice|breakfast|swizzels|lavazza|sainsbury|morrisons|tesco|asda|chocolate/.test(x))return'food';return'other'}
function savePct(d){const m=String(d.save||'').match(/(\d+(?:\.\d+)?)%/);return m?Number(m[1]):0}
function isFree(d){const t=[d.price,d.save,d.deal,d.rule].join(' ').toLowerCase();return parseMoney(d.price)===0||/\bfree\b|100%/.test(t)}
function bestScore(d){let n=0;if(isFree(d))n+=120;const p=savePct(d);if(p>=50)n+=70;else n+=p; if(String(d.stack).includes('YES'))n+=35;if(String(d.status).includes('USE'))n+=15;if(String(d.status).includes('CHECK'))n-=10;const dl=daysLeft(d.expires);if(dl!==null&&dl>=0&&dl<=3)n+=18-dl;return n}
function initMeta(){const old=load(META_KEY,{__init:false});const next=old&&typeof old==='object'?old:{__init:false};if(!next.__init){for(const d of DATA.deals||[]){next[dealKey(d)]={sig:signature(d),badge:'',firstSeen:Date.now()}}next.__init=true}else{for(const d of DATA.deals||[]){const k=dealKey(d),sig=signature(d);if(!next[k])next[k]={sig,badge:'NEW',firstSeen:Date.now()};else if(next[k].sig!==sig){next[k].sig=sig;next[k].badge='CHANGED';next[k].changedAt=Date.now()}}}dealMeta=next;save(META_KEY,next)}
function badgeFor(d){return dealMeta[dealKey(d)]?.badge||''}function acknowledge(d){const k=dealKey(d);if(dealMeta[k]){dealMeta[k].badge='';save(META_KEY,dealMeta)}}
function localClaims(){return load(LOCAL_CLAIMS_KEY,[])}function saveLocalClaims(x){save(LOCAL_CLAIMS_KEY,x)}
function populateShops(){const s=$('#shopSelect');if(!s||!DATA)return;const values=[...new Set((DATA.deals||[]).map(d=>String(d.where||'').trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b));s.innerHTML='<option value="all">All shops</option>'+values.map(v=>'<option value="'+esc(v)+'">'+esc(v)+'</option>').join('');s.value=CURRENT_SHOP}
function updateStats(){if(!DATA||!$('#stats'))return;const live=(DATA.deals||[]).filter(d=>{const n=daysLeft(d.expires);return n===null||n>=0}).length;const changed=(DATA.deals||[]).filter(d=>badgeFor(d)).length;const exp=(DATA.deals||[]).filter(d=>{const n=daysLeft(d.expires);return n!==null&&n>=0&&n<=3}).length;const fav=STATE.favourites.length,basket=STATE.basket.length;$('#stats').innerHTML='<span class="stat">🟢 '+live+' live</span><span class="stat">🆕 '+changed+' new/changed</span><span class="stat">⏰ '+exp+' expiring</span><span class="stat">⭐ '+fav+' saved</span><span class="stat">🛒 '+basket+' shop</span>';const ins=$('#insight');if(ins){if(changed||exp){ins.className='insight show';ins.textContent=(changed?changed+' deal'+(changed===1?'':'s')+' new or changed. ':'')+(exp?exp+' deal'+(exp===1?'':'s')+' end within 3 days.':'')}else ins.className='insight'}}
async function loadData(force=false){setSync('','Syncing…');try{const r=await fetch(DATA_URL+(force?'?v='+Date.now():''),{cache:'no-store'});if(!r.ok)throw Error();DATA=await r.json();if(!DATA||!Array.isArray(DATA.deals))throw Error();save(CACHE_KEY,DATA);setSync('live','Synced • '+(DATA.generatedAt||new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})))}catch{DATA=load(CACHE_KEY,null);if(DATA)setSync('offline','Offline phone copy • '+(DATA.generatedAt||'saved'));else{setSync('offline','No saved copy yet');renderEmpty('No data yet. Tap ↻ to retry.');return}}initMeta();populateShops();updateStats();render();maybeNotify()}
function renderEmpty(msg){if($('#grid'))$('#grid').innerHTML='<div class="empty"><b>Nothing here yet</b>'+esc(msg)+'</div>';if($('#count'))$('#count').textContent='0'}
function dealMatches(d,filter,q){const n=daysLeft(d.expires);if(n!==null&&n<0)return false;const text=Object.values(d).join(' ').toLowerCase();if(q&&!text.includes(q))return false;if(CURRENT_SHOP!=='all'&&String(d.where)!==CURRENT_SHOP)return false;if(filter==='all'||filter==='best')return true;if(filter==='free')return isFree(d);if(filter==='50')return savePct(d)>=50;if(filter==='stack')return String(d.stack).includes('YES');if(filter==='saved')return STATE.favourites.includes(dealKey(d));if(filter==='basket')return STATE.basket.includes(dealKey(d));if(['pet','food','cleaning'].includes(filter))return category(d)===filter;return true}
function renderDeals(){const filter=document.body.dataset.filter||'best',q=($('#search')?.value||'').toLowerCase();let list=(DATA?.deals||[]).filter(d=>dealMatches(d,filter,q));list.sort((a,b)=>filter==='best'?bestScore(b)-bestScore(a):((daysLeft(a.expires)??9999)-(daysLeft(b.expires)??9999)));$('#count').textContent=list.length;$('#grid').innerHTML='';if(!list.length){renderEmpty(filter==='basket'?'Your shopping list is empty. Add a deal with “Add to shop”.':filter==='saved'?'No saved deals yet. Tap the heart on a deal.':'No deals match that view.');return}for(const d of list)$('#grid').appendChild(dealCard(d))}
function dealCard(d){const k=dealKey(d),e=document.createElement('article'),change=badgeFor(d),urgent=expiryBadge(d),dl=safeUrl(d.dealLink);e.className='card '+dealClass(d.status)+(urgent?' expiring':'');const fav=STATE.favourites.includes(k),inBasket=STATE.basket.includes(k),cashback=/cashback/i.test(d.deal+' '+d.rule);e.innerHTML='<div class="row"><div class="badges"><span class="badge">'+esc(String(d.status||'').replace(/^..\s*/,''))+'</span>'+(change?'<span class="changeBadge '+change.toLowerCase()+'">'+change+'</span>':'')+'</div><div style="display:flex;gap:7px;align-items:center">'+(d.price?'<span class="price">'+esc(d.price)+'</span>':'')+'<button class="heart '+(fav?'on':'')+'" data-fav="'+k+'" aria-label="Save deal">'+(fav?'♥':'♡')+'</button></div></div><div class="title">'+esc(d.deal)+'</div><div class="meta">'+(d.save?'<span class="pill">SAVE '+esc(d.save)+'</span>':'')+(d.where?'<span class="pill">'+esc(d.where)+'</span>':'')+(d.stack?'<span class="pill '+stackClass(d.stack)+'">STACK '+esc(String(d.stack).replace(/^..\s*/,''))+'</span>':'')+(urgent?'<span class="pill urgent">'+urgent+'</span>':d.expires?'<span class="pill">EXP '+esc(d.expires)+'</span>':'')+'</div>'+(d.code?'<div class="codebox"><span class="code">'+esc(d.code)+'</span><button class="copy" data-copy="'+esc(d.code)+'">Copy</button></div>':'')+(d.rule?'<div class="rule">'+esc(d.rule)+'</div>':'')+'<div class="buttons"><button class="btn" data-details="'+k+'">Details</button><button class="btn '+(inBasket?'good':'')+'" data-basket="'+k+'">'+(inBasket?'✓ In shop':'Add to shop')+'</button><a class="btn primary '+(!dl?'disabled':'')+'" '+(dl?'href="'+esc(dl)+'" target="_blank" rel="noopener"':'')+'>Get deal</a>'+(cashback?'<button class="btn full good" data-bought="'+k+'">🧾 I bought this cashback deal</button>':'')+'</div>';return e}
function findDeal(k){return (DATA?.deals||[]).find(d=>dealKey(d)===k)}
function openModal(title,html){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=html;$('#appModal').showModal()}
function detailHtml(d){const dl=safeUrl(d.dealLink),tl=safeUrl(d.terms);const fields=[['What to buy',d.deal],['Where',d.where],['Final price',d.price||'Not stated'],['Saving',d.save||'Not stated'],['Code / voucher',d.code||'None stated'],['Stacking',d.stack||'Unclear'],['Expiry',d.expires||'No fixed date stated'],['Limits / rules',d.rule||'No extra rule recorded']];return '<div class="detailGrid">'+fields.map(x=>'<div class="detail"><small>'+esc(x[0])+'</small><strong>'+esc(x[1])+'</strong></div>').join('')+'</div><div class="modalActions">'+(dl?'<a class="btn primary" href="'+esc(dl)+'" target="_blank" rel="noopener">Open deal</a>':'')+(tl?'<a class="btn" href="'+esc(tl)+'" target="_blank" rel="noopener">Official terms</a>':'')+'</div><div class="utilityNote">Coupon Hunt only labels a stack verified when the recorded terms support the combination. CHECK means something is still unclear.</div>'}
function toggle(listName,k){const a=STATE[listName];const i=a.indexOf(k);if(i>=0)a.splice(i,1);else a.push(k);stateSave();updateStats();render()}
function basketHtml(){const items=STATE.basket.map(findDeal).filter(Boolean),groups={};for(const d of items)(groups[d.where||'Other']??=[]).push(d);let total=0,known=0,unknown=0;for(const d of items){const p=parseMoney(d.price);if(p===null)unknown++;else{total+=p;known++}}let html='<div class="basketTotal"><small>Known final total</small><br><strong>£'+total.toFixed(2)+'</strong><div class="utilityNote">'+known+' priced item'+(known===1?'':'s')+(unknown?' • '+unknown+' price'+(unknown===1?'':'s')+' not stated':'')+'</div></div>';for(const [shop,arr] of Object.entries(groups)){html+='<div class="basketGroup"><h3>🏪 '+esc(shop)+'</h3>'+arr.map(d=>'<div class="basketItem"><div><b>'+esc(d.deal)+'</b><small>'+(d.code?'Code: '+esc(d.code)+' • ':'')+(d.price?'Final '+esc(d.price):'Price not stated')+'</small></div><button class="btn danger" data-basket="'+dealKey(d)+'">Remove</button></div>').join('')+'</div>'}if(!items.length)html='<div class="empty"><b>Your shopping list is empty</b>Add deals from the Deals tab.</div>';return html}
function renderCoupons(){const x=(DATA?.coupons||[]).filter(c=>c.brand);$('#count').textContent=x.length;$('#grid').innerHTML='';if(!x.length){renderEmpty('No coupons saved yet.');return}for(const c of x){const k=couponKey(c),used=STATE.usedCoupons.includes(k),m=String(c.coupon||'').match(/(?:–|-|code\s*)([A-Z][A-Z0-9-]{3,})\b/i),code=m?m[1].toUpperCase():'';const e=document.createElement('article');e.className='card'+(used?' used':'');e.innerHTML='<div class="row"><div class="badges"><span class="badge">'+esc(c.status||'Coupon')+'</span></div>'+(c.value?'<span class="price">£'+esc(c.value)+'</span>':'')+'</div><div class="title">'+esc(c.brand+' • '+c.coupon)+'</div><div class="meta">'+(c.expiry?'<span class="pill">EXP '+esc(c.expiry)+'</span>':'')+(c.stores?'<span class="pill">'+esc(c.stores)+'</span>':'')+'</div>'+(code?'<div class="codebox"><span class="code">'+esc(code)+'</span><button class="copy" data-copy="'+esc(code)+'">Copy</button></div>':'')+'<div class="rule">'+esc(c.rules||'')+(c.notes?' • '+esc(c.notes):'')+'</div><div class="buttons"><button class="btn '+(used?'good':'')+'" data-used-coupon="'+k+'">'+(used?'✓ Used':'Mark used')+'</button>'+(code?'<button class="btn" data-copy="'+esc(code)+'">Copy code</button>':'')+'<button class="btn" data-coupon-details="'+k+'">Details</button></div>';e.dataset.couponKey=k;$('#grid').appendChild(e)}}
function renderClaims(){const src=DATA?.claims||[],local=localClaims();$('#count').textContent=src.length+local.length;$('#grid').innerHTML='';for(const c of src){const e=document.createElement('article');e.className='card';e.innerHTML='<div class="title">'+esc(c.product||c.dealId||c.claimId)+'</div><div class="meta">'+[c.status,c.provider,c.claimDeadline&&'CLAIM '+c.claimDeadline].filter(Boolean).map(x=>'<span class="pill">'+esc(x)+'</span>').join('')+'</div><div class="rule">'+esc(c.notes||'')+'</div>';$('#grid').appendChild(e)}for(const c of local){const e=document.createElement('article');e.className='card';e.innerHTML='<div class="row"><span class="badge">PHONE</span><span class="pill '+(c.status==='Paid'?'yes':'warn')+'">'+esc(c.status)+'</span></div><div class="title">'+esc(c.product)+'</div><div class="meta"><span class="pill">BOUGHT '+esc(c.purchaseDate)+'</span>'+(c.provider?'<span class="pill">'+esc(c.provider)+'</span>':'')+'</div><div class="rule">Saved on this phone. Check the official offer terms for the real claim deadline unless Coupon Hunt has one recorded.</div><div class="buttons"><button class="btn" data-claim-status="'+c.id+'" data-status="Submitted">Submitted</button><button class="btn good" data-claim-status="'+c.id+'" data-status="Paid">Paid</button><button class="btn danger" data-remove-claim="'+c.id+'">Remove</button></div>';$('#grid').appendChild(e)}if(!src.length&&!local.length)renderEmpty('No claims waiting. Tap “I bought this cashback deal” on a cashback offer to start tracking it here.')}
function renderSubs(){const x=(DATA?.subscriptions||[]).filter(s=>s.brand);$('#count').textContent=x.length;$('#grid').innerHTML='';if(!x.length){renderEmpty('No subscription offers being watched.');return}for(const s of x){const k=subKey(s),watch=STATE.watchedSubs.includes(k),e=document.createElement('article');e.className='card check';e.innerHTML='<div class="row"><span class="badge">SUBSCRIPTION</span><button class="heart '+(watch?'on':'')+'" data-watch-sub="'+k+'">'+(watch?'♥':'♡')+'</button></div><div class="title">'+esc(s.brand+' • '+s.product)+'</div><div class="meta">'+[s.status,s.delivery&&'DELIVERY '+s.delivery].filter(Boolean).map(x=>'<span class="pill">'+esc(x)+'</span>').join('')+'</div><div class="safety"><b>⚠ Subscription safety</b><p>'+(s.start?'<b>Starts:</b> '+esc(s.start)+'<br>':'')+(s.nextCharge?'<b>Next charge:</b> '+esc(s.nextCharge)+'<br>':'')+(s.renewal?'<b>Ongoing:</b> '+esc(s.renewal)+'<br>':'')+(s.cancelBy?'<b>Cancel/change:</b> '+esc(s.cancelBy):'Cancel deadline not recorded')+'</p></div><div class="rule">'+esc(s.notes||'')+'</div><div class="buttons"><button class="btn '+(watch?'good':'')+'" data-watch-sub="'+k+'">'+(watch?'✓ Watching':'Watch this')+'</button></div>';$('#grid').appendChild(e)}}
function renderInstore(){const x=DATA?.instore||[];$('#count').textContent=x.length;$('#grid').innerHTML='';if(!x.length){const basket=STATE.basket.map(findDeal).filter(d=>d&&/tesco|asda|morrisons|sainsbury|waitrose|pets at home|retail|store/i.test(d.where||''));if(basket.length){for(const d of basket)$('#grid').appendChild(dealCard(d));return}renderEmpty('No fully verified walk-in missions yet. Retail deals added to your shopping list will also appear here.');return}for(const i of x){const e=document.createElement('article');e.className='card use';e.innerHTML='<div class="title">'+esc(i.brand+' • '+i.product)+'</div><div class="meta">'+[i.retailer,i.final&&'FINAL '+i.final,i.stack&&'STACK '+i.stack,i.buyBy&&'BUY '+i.buyBy].filter(Boolean).map(x=>'<span class="pill">'+esc(x)+'</span>').join('')+'</div><div class="rule">'+esc(i.inShop||'')+(i.after?' • '+esc(i.after):'')+'</div>';$('#grid').appendChild(e)}}
function render(){if(!DATA)return;const v=document.body.dataset.view||'deals';updateStats();if(v==='deals')renderDeals();if(v==='coupons')renderCoupons();if(v==='claims')renderClaims();if(v==='subs')renderSubs();if(v==='instore')renderInstore()}
function addLocalClaim(d){const x=localClaims(),id='lc_'+Date.now();x.unshift({id,dealKey:dealKey(d),product:d.deal,provider:d.where,purchaseDate:new Date().toLocaleDateString('en-GB'),status:'Purchased',terms:d.terms});saveLocalClaims(x);openModal('Claim tracker','<div class="detail"><small>Added</small><strong>'+esc(d.deal)+'</strong></div><div class="utilityNote">It is now in Claims. Coupon Hunt has not invented a claim deadline. Use the official terms until a verified deadline is recorded.</div>')}
async function toggleAlerts(){if(!('Notification'in window)){openModal('Alerts','<div class="utilityNote">This browser does not support app notifications. Expiry warnings will still appear inside Coupon Hunt.</div>');return}if(Notification.permission!=='granted'){const p=await Notification.requestPermission();if(p!=='granted')return}STATE.alerts=!STATE.alerts;stateSave();$('#alertsBtn').textContent=STATE.alerts?'🔔':'🔕';if(STATE.alerts)maybeNotify()}
function maybeNotify(){if(!STATE.alerts||!('Notification'in window)||Notification.permission!=='granted'||!DATA)return;const exp=(DATA.deals||[]).filter(d=>{const n=daysLeft(d.expires);return n!==null&&n>=0&&n<=3}).length,newc=(DATA.deals||[]).filter(d=>badgeFor(d)).length,key=new Date().toISOString().slice(0,10)+'|'+exp+'|'+newc;if(key===STATE.lastNotify||(!exp&&!newc))return;STATE.lastNotify=key;stateSave();navigator.serviceWorker?.ready.then(r=>r.showNotification('Coupon Hunt HQ',{body:(newc?newc+' new/changed deal'+(newc===1?'':'s')+'. ':'')+(exp?exp+' deal'+(exp===1?'':'s')+' expiring soon.':''),icon:'./icon.svg',tag:'coupon-hunt-summary'})).catch(()=>{})}
document.addEventListener('click',e=>{const cp=e.target.closest('[data-copy]');if(cp){navigator.clipboard?.writeText(cp.dataset.copy);cp.textContent='Copied';setTimeout(()=>cp.textContent='Copy',900);return}const f=e.target.closest('[data-filter]');if(f){$$('[data-filter]').forEach(x=>x.classList.remove('active'));f.classList.add('active');document.body.dataset.filter=f.dataset.filter;renderDeals();return}const fav=e.target.closest('[data-fav]');if(fav){toggle('favourites',fav.dataset.fav);return}const b=e.target.closest('[data-basket]');if(b){toggle('basket',b.dataset.basket);if($('#appModal')?.open){$('#modalBody').innerHTML=basketHtml()}return}const det=e.target.closest('[data-details]');if(det){const d=findDeal(det.dataset.details);if(d){acknowledge(d);openModal('Deal details',detailHtml(d));updateStats();renderDeals()}return}const bought=e.target.closest('[data-bought]');if(bought){const d=findDeal(bought.dataset.bought);if(d)addLocalClaim(d);return}if(e.target.closest('#markSeen')){for(const k of Object.keys(dealMeta))if(dealMeta[k]?.badge)dealMeta[k].badge='';save(META_KEY,dealMeta);updateStats();renderDeals();return}if(e.target.closest('#alertsBtn')){toggleAlerts();return}if(e.target.closest('#refresh')){loadData(true);return}if(e.target.closest('#install')&&deferredInstall){deferredInstall.prompt();deferredInstall=null;$('#install').hidden=true;return}if(e.target.closest('[data-close-modal]')){$('#appModal').close();return}const uc=e.target.closest('[data-used-coupon]');if(uc){toggle('usedCoupons',uc.dataset.usedCoupon);return}const ws=e.target.closest('[data-watch-sub]');if(ws){toggle('watchedSubs',ws.dataset.watchSub);return}const cs=e.target.closest('[data-claim-status]');if(cs){const x=localClaims(),c=x.find(a=>a.id===cs.dataset.claimStatus);if(c){c.status=cs.dataset.status;saveLocalClaims(x);renderClaims()}return}const rc=e.target.closest('[data-remove-claim]');if(rc){saveLocalClaims(localClaims().filter(a=>a.id!==rc.dataset.removeClaim));renderClaims();return}});
document.addEventListener('change',e=>{if(e.target.id==='shopSelect'){CURRENT_SHOP=e.target.value;renderDeals()}});
document.addEventListener('input',e=>{if(e.target.id==='search')renderDeals()});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;if($('#install'))$('#install'].hidden=false});
window.addEventListener('online',()=>loadData(true));
ensureV6Css();upgradeShell();if($('#alertsBtn'))$('#alertsBtn').textContent=STATE.alerts?'🔔':'🔕';if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js?v=6');loadData(true);
})();